# Generated by Django 4.1.6 on 2023-03-10 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=20)),
                ('signature', models.CharField(max_length=20)),
                ('vibe', models.CharField(max_length=250)),
                ('lyric', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jammerplannerapi.user')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jammerplannerapi.band')),
            ],
        ),
        migrations.CreateModel(
            name='Set_Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=50)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_songs', to='jammerplannerapi.set')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_songs', to='jammerplannerapi.song')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jammerplannerapi.user'),
        ),
        migrations.AddField(
            model_name='set',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jammerplannerapi.band'),
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('show', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jammerplannerapi.user')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jammerplannerapi.band')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jammerplannerapi.set')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jammerplannerapi.user')),
                ('rehearse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jammerplannerapi.rehearsal')),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jammerplannerapi.user'),
        ),
    ]
