# Generated by Django 4.1.6 on 2023-03-10 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jammerplannerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set_song',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_songs', to='jammerplannerapi.set'),
        ),
        migrations.AlterField(
            model_name='set_song',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_songs', to='jammerplannerapi.song'),
        ),
    ]
